title: Garden Flora Observer
description: >- # this means to ignore newlines until "baseurl:"
  A catalogue of all the flora in my garden.
baseurl: "/" 
css-dir: "assets/css/"
js-dir: "assets/js/"
linkedin: "https://www.linkedin.com/in/christanfergus/"
personal-site: "https://christanfergus.com"
url: "https://gardenflora.observer" 
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .DS_Store
markdown: kramdown
future: true
sass:
  sass_dir: assets/stylesheets
  style: compressed
  sourcemap: always 
assets:
  source_maps: true
  sources:
  - assets/stylesheets
garden-location: Thornton, Colorado
hardiness-zone: 5b
plugins: 
  - jekyll-paginate
paginate: 5
